#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR/..
npm ci

npx shadow-cljs node-test ; node -r source-map-support/register target/node-test/node-tests.js
