name: Run tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Run Clojure tests
      run: clj -T:build ci
    - name: Run ClojureScript tests
      run: ./scripts/shadow-run-tests
